#!/usr/bin/env python

import subprocess
from sense_hat import SenseHat
from time import sleep

sense = SenseHat()

message = subprocess.check_output("docker node ls | awk '{ if ($2 != \"*\") { print $2, \" \", $4 } else { print $3, \" \", $5 } }'; exit 0", stderr=subprocess.STDOUT, shell=True)

sense.show_message(message, scroll_speed=0.1, text_colour=[100, 100, 100])
sense.clear()
sleep(300)


